name: Verify completions

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "7 10 1 * *"  # at 10:07 on the first day of every month (i.e. monthly)
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify-completions:
    runs-on: ubuntu-latest
    env:
      CONAN_VERSION: '1.53.0'
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - name: Install conan ${{ env.CONAN_VERSION }}
        run: |
          python3 -m pip install conan==${{ env.CONAN_VERSION }}
      - name: Re-generation completions file
        run: |
          python3 -B generate_fish_conan_completions.py > completions/conan-${{ env.CONAN_VERSION }}.fish
      - name: Check if up-to-date
        run: |
          exit $(git diff --name-only | wc -l)

      - name: Install fish
        run: |
          sudo apt-get update
          sudo apt-get install fish
      - name: Check syntax of the completions file
        run: |
          fish --no-execute completions/conan-${{ env.CONAN_VERSION }}.fish
